import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import {
  User,
  Category,
  Product,
  Customer,
  Supplier,
  Invoice,
  InvoiceItem,
  StockTransaction,
  CustomerLedgerEntry,
  SupplierLedgerEntry,
  ReturnRecord,
  BusinessSettings,
  AuditLog,
  Payment,
  DashboardStats,
} from '../types/index.js';

const DATA_DIR = path.join(process.cwd(), 'data');
const DB_FILE = path.join(DATA_DIR, 'db.json');

interface DatabaseSchema {
  users: (User & { passwordHash: string })[];
  categories: Category[];
  products: Product[];
  customers: Customer[];
  suppliers: Supplier[];
  invoices: Invoice[];
  payments: Payment[];
  stockTransactions: StockTransaction[];
  customerLedgers: CustomerLedgerEntry[];
  supplierLedgers: SupplierLedgerEntry[];
  returns: ReturnRecord[];
  settings: BusinessSettings;
  auditLogs: AuditLog[];
}

let dbCache: DatabaseSchema | null = null;

function ensureDataDir() {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
}

export function getInitialData(): DatabaseSchema {
  const salt = bcrypt.genSaltSync(10);
  const adminHash = bcrypt.hashSync('admin123', salt);
  const staffHash = bcrypt.hashSync('staff123', salt);

  const defaultUsers: (User & { passwordHash: string })[] = [
    {
      id: 'usr-admin',
      username: 'admin',
      email: 'admin@smautos.com',
      role: 'admin',
      name: 'Sardar Manjit Singh',
      phone: '+91 98765 43210',
      passwordHash: adminHash,
      createdAt: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'usr-staff',
      username: 'staff',
      email: 'staff@smautos.com',
      role: 'staff',
      name: 'Rohan Sharma',
      phone: '+91 98111 22334',
      passwordHash: staffHash,
      createdAt: '2026-01-15T09:30:00.000Z',
    },
  ];

  const defaultCategories: Category[] = [
    { id: 'cat-1', name: 'Car Batteries', description: 'Lead-acid & AGM batteries for hatchbacks, sedans, SUVs', productCount: 4, createdAt: '2026-01-01' },
    { id: 'cat-2', name: 'Bike Batteries', description: 'Zero-maintenance batteries for 2-wheelers', productCount: 3, createdAt: '2026-01-01' },
    { id: 'cat-3', name: 'Commercial & Inverter Batteries', description: 'Heavy-duty batteries for trucks, tractors & home inverters', productCount: 2, createdAt: '2026-01-01' },
    { id: 'cat-4', name: 'Engine Oils & Lubricants', description: 'Synthetic, semi-synthetic & mineral engine oils', productCount: 4, createdAt: '2026-01-01' },
    { id: 'cat-5', name: 'Brake Pads & Shoes', description: 'Ceramic and metallic brake friction pads', productCount: 3, createdAt: '2026-01-01' },
    { id: 'cat-6', name: 'Filters & Spark Plugs', description: 'Oil filters, air filters, cabin filters and iridium plugs', productCount: 3, createdAt: '2026-01-01' },
    { id: 'cat-7', name: 'Electrical & Horns', description: 'Horns, relays, LED bulbs, alternators', productCount: 2, createdAt: '2026-01-01' },
    { id: 'cat-8', name: 'Accessories & Car Care', description: 'Coolant, battery terminals, distill water, polish', productCount: 2, createdAt: '2026-01-01' },
  ];

  const defaultSuppliers: Supplier[] = [
    {
      id: 'sup-1',
      name: 'Exide Industries Ltd - Regional Depot',
      contactPerson: 'Harpreet Singh',
      phone: '+91 98100 12345',
      email: 'delhi.sales@exide.co.in',
      address: 'Plot 44, Okhla Industrial Area Phase 2, New Delhi',
      gstin: '07AAACE0123L1Z4',
      openingBalance: 0,
      currentPayable: 35000,
      paymentTerms: '30 Days Net',
      createdAt: '2026-01-02',
    },
    {
      id: 'sup-2',
      name: 'Amaron Battery Distribution Hub',
      contactPerson: 'Sunil Mittal',
      phone: '+91 98200 67890',
      email: 'orders@amaronhub.com',
      address: 'Shop 18, Transport Nagar, GT Road, Delhi',
      gstin: '07AABCA9876D1Z1',
      openingBalance: 0,
      currentPayable: 18500,
      paymentTerms: '15 Days Net',
      createdAt: '2026-01-03',
    },
    {
      id: 'sup-3',
      name: 'Castrol Lubricants Distributor',
      contactPerson: 'Deepak Varma',
      phone: '+91 98300 54321',
      email: 'varma.lubes@gmail.com',
      address: 'Godown 7, Kashmere Gate Auto Spares Complex, Delhi',
      gstin: '07AAACC4321F1ZX',
      openingBalance: 0,
      currentPayable: 12000,
      paymentTerms: 'Immediate / 7 Days',
      createdAt: '2026-01-04',
    },
    {
      id: 'sup-4',
      name: 'Bosch Automotive Aftermarket Spares',
      contactPerson: 'Rajiv Mehra',
      phone: '+91 98400 99887',
      email: 'north.sales@bosch-spares.in',
      address: 'B-12, Mayapuri Industrial Area, Delhi',
      gstin: '07AAACB5678H1Z3',
      openingBalance: 0,
      currentPayable: 8400,
      paymentTerms: '21 Days Net',
      createdAt: '2026-01-05',
    },
  ];

  const defaultCustomers: Customer[] = [
    {
      id: 'cust-1',
      name: 'Verma Motors & Multi-Brand Workshop',
      phone: '9810123456',
      alternatePhone: '9810123457',
      address: 'Plot 10, Auto Cluster, Sector 18, Rohini, Delhi',
      gstin: '07AADFV5566K1Z9',
      email: 'vermamotors@gmail.com',
      customerType: 'Garage/Mechanic',
      openingBalance: 0,
      creditLimit: 50000,
      currentOutstanding: 14500,
      notes: 'Regular workshop customer. Buys batteries and bulk lubricants.',
      createdAt: '2026-01-10',
    },
    {
      id: 'cust-2',
      name: 'Vikas Auto Clinic',
      phone: '9871234560',
      alternatePhone: '',
      address: 'Shop 4, Near Metro Pillar 321, GT Road, Delhi',
      gstin: '07BBBPV9988P1Z2',
      email: 'vikas.autoclinic@yahoo.com',
      customerType: 'Garage/Mechanic',
      openingBalance: 0,
      creditLimit: 30000,
      currentOutstanding: 8200,
      notes: 'Weekly settling customer.',
      createdAt: '2026-01-12',
    },
    {
      id: 'cust-3',
      name: 'Rajesh Sharma',
      phone: '9899001122',
      address: 'Flat 204, Pocket B, Ashok Vihar, Delhi',
      customerType: 'Retail',
      openingBalance: 0,
      creditLimit: 5000,
      currentOutstanding: 0,
      notes: 'Retail car owner (Swift Dzire). Bought Amaron battery.',
      createdAt: '2026-01-15',
    },
    {
      id: 'cust-4',
      name: 'Speedex Logistics & Cabs',
      phone: '9811445566',
      address: 'Transport Nagar Gate 2, Delhi',
      gstin: '07AAACS7788L1Z6',
      customerType: 'Wholesale',
      openingBalance: 0,
      creditLimit: 100000,
      currentOutstanding: 28400,
      notes: 'Fleet of 25 commercial vehicles. Bulk purchase of oil and batteries.',
      createdAt: '2026-01-18',
    },
    {
      id: 'cust-5',
      name: 'Manish Tyagi',
      phone: '9822334455',
      address: 'House 88, Model Town 2, Delhi',
      customerType: 'Retail',
      openingBalance: 0,
      creditLimit: 0,
      currentOutstanding: 0,
      notes: 'Royal Enfield Classic 350 owner.',
      createdAt: '2026-02-01',
    },
  ];

  const defaultProducts: Product[] = [
    {
      id: 'prod-1',
      sku: 'BAT-EX-MI45L',
      name: 'Exide Mileage MLDIN45L (45 Ah) Car Battery',
      category: 'Car Batteries',
      brand: 'Exide',
      modelNumber: 'MLDIN45L',
      barcode: '890123400101',
      description: 'Zero maintenance automotive battery suitable for Hyundai i20, Creta, Verna, Maruti Swift Diesel.',
      purchasePrice: 4200,
      sellingPrice: 5350,
      mrp: 6499,
      gstRate: 28,
      discountPercent: 5,
      openingStock: 25,
      currentStock: 18,
      minStockLevel: 5,
      unit: 'Nos',
      supplierId: 'sup-1',
      supplierName: 'Exide Industries Ltd - Regional Depot',
      warrantyPeriod: '55 Months (30 FOC + 25 Pro-rata)',
      status: 'active',
      createdAt: '2026-01-05',
      updatedAt: '2026-01-05',
    },
    {
      id: 'prod-2',
      sku: 'BAT-AM-FLO35R',
      name: 'Amaron Flo AAM-FL-00042B20R (35 Ah) Battery',
      category: 'Car Batteries',
      brand: 'Amaron',
      modelNumber: 'AAM-FL-00042B20R',
      barcode: '890123400102',
      description: 'Long life silver alloy battery for Maruti Alto, WagonR, Celerio, Santro, Eeco.',
      purchasePrice: 3200,
      sellingPrice: 4100,
      mrp: 4999,
      gstRate: 28,
      discountPercent: 4,
      openingStock: 20,
      currentStock: 4, // LOW STOCK ALERT (<= 5)
      minStockLevel: 6,
      unit: 'Nos',
      supplierId: 'sup-2',
      supplierName: 'Amaron Battery Distribution Hub',
      warrantyPeriod: '60 Months (36 FOC + 24 Pro-rata)',
      status: 'active',
      createdAt: '2026-01-05',
      updatedAt: '2026-01-05',
    },
    {
      id: 'prod-3',
      sku: 'BAT-AM-PRO5L',
      name: 'Amaron Pro Rider AP-BTX5L (5 Ah) Bike Battery',
      category: 'Bike Batteries',
      brand: 'Amaron',
      modelNumber: 'AP-BTX5L',
      barcode: '890123400103',
      description: 'Maintenance free VRLA battery for Honda Activa, Hero Splendor, Passion Pro, Shine.',
      purchasePrice: 950,
      sellingPrice: 1350,
      mrp: 1650,
      gstRate: 28,
      discountPercent: 0,
      openingStock: 40,
      currentStock: 26,
      minStockLevel: 10,
      unit: 'Nos',
      supplierId: 'sup-2',
      supplierName: 'Amaron Battery Distribution Hub',
      warrantyPeriod: '48 Months',
      status: 'active',
      createdAt: '2026-01-05',
      updatedAt: '2026-01-05',
    },
    {
      id: 'prod-4',
      sku: 'BAT-EX-XP9B',
      name: 'Exide Xplore 12XL9-B (9 Ah) Heavy Bike Battery',
      category: 'Bike Batteries',
      brand: 'Exide',
      modelNumber: '12XL9-B',
      barcode: '890123400104',
      description: 'High cranking power for Royal Enfield Bullet 350, Classic 500, Bajaj Pulsar 220.',
      purchasePrice: 1600,
      sellingPrice: 2150,
      mrp: 2650,
      gstRate: 28,
      discountPercent: 0,
      openingStock: 15,
      currentStock: 2, // LOW STOCK ALERT
      minStockLevel: 4,
      unit: 'Nos',
      supplierId: 'sup-1',
      supplierName: 'Exide Industries Ltd - Regional Depot',
      warrantyPeriod: '48 Months',
      status: 'active',
      createdAt: '2026-01-06',
      updatedAt: '2026-01-06',
    },
    {
      id: 'prod-5',
      sku: 'BAT-EX-INV150',
      name: 'Exide Inva Tubular IT500 (150 Ah) Tall Tubular Battery',
      category: 'Commercial & Inverter Batteries',
      brand: 'Exide',
      modelNumber: 'IT500-150AH',
      barcode: '890123400105',
      description: 'Heavy duty tall tubular deep cycle battery for home and commercial shop inverters.',
      purchasePrice: 10800,
      sellingPrice: 13900,
      mrp: 17500,
      gstRate: 28,
      discountPercent: 5,
      openingStock: 12,
      currentStock: 0, // OUT OF STOCK
      minStockLevel: 3,
      unit: 'Nos',
      supplierId: 'sup-1',
      supplierName: 'Exide Industries Ltd - Regional Depot',
      warrantyPeriod: '66 Months (36 FOC + 30 Pro-rata)',
      status: 'active',
      createdAt: '2026-01-06',
      updatedAt: '2026-01-06',
    },
    {
      id: 'prod-6',
      sku: 'OIL-CAS-EDG5W40',
      name: 'Castrol EDGE 5W-40 Fully Synthetic Engine Oil (4L)',
      category: 'Engine Oils & Lubricants',
      brand: 'Castrol',
      modelNumber: 'EDGE-5W40-4L',
      barcode: '890123400106',
      description: 'Fluid TITANIUM technology for maximum engine performance in premium petrol and diesel cars.',
      purchasePrice: 2450,
      sellingPrice: 3250,
      mrp: 3899,
      gstRate: 18,
      discountPercent: 5,
      openingStock: 30,
      currentStock: 16,
      minStockLevel: 5,
      unit: 'Nos',
      supplierId: 'sup-3',
      supplierName: 'Castrol Lubricants Distributor',
      warrantyPeriod: 'N/A (Sealed Pack)',
      status: 'active',
      createdAt: '2026-01-08',
      updatedAt: '2026-01-08',
    },
    {
      id: 'prod-7',
      sku: 'OIL-MOT-7100',
      name: 'Motul 7100 4T 10W-50 100% Synthetic Bike Oil (1L)',
      category: 'Engine Oils & Lubricants',
      brand: 'Motul',
      modelNumber: '7100-10W50-1L',
      barcode: '890123400107',
      description: 'Ester technology bike lubricant for sports bikes like KTM Duke, RC, Dominar, RE 650.',
      purchasePrice: 720,
      sellingPrice: 980,
      mrp: 1190,
      gstRate: 18,
      discountPercent: 0,
      openingStock: 50,
      currentStock: 38,
      minStockLevel: 10,
      unit: 'Nos',
      supplierId: 'sup-3',
      supplierName: 'Castrol Lubricants Distributor',
      warrantyPeriod: 'N/A',
      status: 'active',
      createdAt: '2026-01-08',
      updatedAt: '2026-01-08',
    },
    {
      id: 'prod-8',
      sku: 'BRK-BOS-SWF',
      name: 'Bosch Front Disc Brake Pads Set for Maruti Swift / Dzire',
      category: 'Brake Pads & Shoes',
      brand: 'Bosch',
      modelNumber: 'BP-SWIFT-FR',
      barcode: '890123400108',
      description: 'Asbestos-free premium ceramic friction brake pads with noise-reduction shims.',
      purchasePrice: 650,
      sellingPrice: 950,
      mrp: 1250,
      gstRate: 18,
      discountPercent: 0,
      openingStock: 25,
      currentStock: 14,
      minStockLevel: 5,
      unit: 'Sets',
      supplierId: 'sup-4',
      supplierName: 'Bosch Automotive Aftermarket Spares',
      warrantyPeriod: '6 Months',
      status: 'active',
      createdAt: '2026-01-10',
      updatedAt: '2026-01-10',
    },
    {
      id: 'prod-9',
      sku: 'FLT-BOS-AIR-HY',
      name: 'Bosch Engine Air Filter for Hyundai Creta / Seltos',
      category: 'Filters & Spark Plugs',
      brand: 'Bosch',
      modelNumber: 'AF-CRETA-01',
      barcode: '890123400109',
      description: 'Micro-fibre high-capacity air filtration element for optimal airflow and engine protection.',
      purchasePrice: 280,
      sellingPrice: 420,
      mrp: 550,
      gstRate: 18,
      discountPercent: 0,
      openingStock: 20,
      currentStock: 3, // LOW STOCK ALERT
      minStockLevel: 5,
      unit: 'Nos',
      supplierId: 'sup-4',
      supplierName: 'Bosch Automotive Aftermarket Spares',
      warrantyPeriod: 'N/A',
      status: 'active',
      createdAt: '2026-01-10',
      updatedAt: '2026-01-10',
    },
    {
      id: 'prod-10',
      sku: 'ELC-ROO-WND',
      name: 'Roots Windtone Sonic Dual Horn Set (12V)',
      category: 'Electrical & Horns',
      brand: 'Roots',
      modelNumber: 'WINDTONE-90',
      barcode: '890123400110',
      description: 'Original European tone dual trumpet horn set with relay wire harness.',
      purchasePrice: 620,
      sellingPrice: 890,
      mrp: 1150,
      gstRate: 18,
      discountPercent: 0,
      openingStock: 15,
      currentStock: 11,
      minStockLevel: 4,
      unit: 'Sets',
      supplierId: 'sup-4',
      supplierName: 'Bosch Automotive Aftermarket Spares',
      warrantyPeriod: '12 Months',
      status: 'active',
      createdAt: '2026-01-10',
      updatedAt: '2026-01-10',
    },
    {
      id: 'prod-11',
      sku: 'SPK-NGK-IRID',
      name: 'NGK Laser Iridium Spark Plug CPR8EAIX-9',
      category: 'Filters & Spark Plugs',
      brand: 'NGK',
      modelNumber: 'CPR8EAIX-9',
      barcode: '890123400111',
      description: 'Ultra fine 0.6mm laser welded iridium tip for instant ignition and fuel efficiency.',
      purchasePrice: 480,
      sellingPrice: 690,
      mrp: 850,
      gstRate: 18,
      discountPercent: 0,
      openingStock: 30,
      currentStock: 22,
      minStockLevel: 6,
      unit: 'Nos',
      supplierId: 'sup-4',
      supplierName: 'Bosch Automotive Aftermarket Spares',
      warrantyPeriod: '12 Months',
      status: 'active',
      createdAt: '2026-01-10',
      updatedAt: '2026-01-10',
    },
    {
      id: 'prod-12',
      sku: 'ACC-DIST-5L',
      name: 'SM Battery Grade De-mineralized Distilled Water (5 Litres)',
      category: 'Accessories & Car Care',
      brand: 'SM AutoCare',
      modelNumber: 'DW-5L',
      barcode: '890123400112',
      description: 'Pure lab-tested zero conductivity battery top-up water with easy pour nozzle.',
      purchasePrice: 45,
      sellingPrice: 90,
      mrp: 120,
      gstRate: 12,
      discountPercent: 0,
      openingStock: 60,
      currentStock: 45,
      minStockLevel: 15,
      unit: 'Nos',
      supplierId: 'sup-2',
      supplierName: 'Amaron Battery Distribution Hub',
      warrantyPeriod: 'N/A',
      status: 'active',
      createdAt: '2026-01-12',
      updatedAt: '2026-01-12',
    },
  ];

  const defaultSettings: BusinessSettings = {
    businessName: 'SM Autos & Batteries',
    tagline: 'Automotive Batteries, Lubricants & Genuine Spares',
    address: 'Shop No. 12, Main Auto Market, Opp. Transport Nagar, GT Road',
    city: 'Delhi',
    state: 'Delhi',
    stateCode: '07',
    pincode: '110033',
    phone: '+91 98765 43210',
    alternatePhone: '+91 98111 22334',
    email: 'billing@smautos.com',
    gstin: '07AABCS1234M1Z8',
    pan: 'AABCS1234M',
    invoicePrefix: 'SMA-2026',
    nextInvoiceNumber: 1006,
    termsAndConditions:
      '1. Goods once sold will be exchanged or returned within 7 days only against valid invoice.\n2. Battery warranty must be registered on manufacturer portal or claimed with original guarantee card.\n3. All electrical items carry manufacturer warranty only.\n4. Subject to Delhi jurisdiction only.',
    bankName: 'HDFC Bank Ltd',
    bankAccount: '50200012345678',
    ifscCode: 'HDFC0001234',
    bankBranch: 'GT Road Azadpur, Delhi',
    upiId: 'smautos@hdfcbank',
    defaultGstRate: 18,
    maxDiscountPercent: 25,
  };

  const defaultStockTransactions: StockTransaction[] = [
    {
      id: 'stk-1',
      productId: 'prod-1',
      productName: 'Exide Mileage MLDIN45L (45 Ah) Car Battery',
      type: 'opening',
      quantity: 25,
      previousStock: 0,
      updatedStock: 25,
      userId: 'usr-admin',
      userName: 'Sardar Manjit Singh',
      remarks: 'Initial stock intake from Exide Depot',
      date: '2026-01-05T10:00:00.000Z',
    },
    {
      id: 'stk-2',
      productId: 'prod-2',
      productName: 'Amaron Flo AAM-FL-00042B20R (35 Ah) Battery',
      type: 'opening',
      quantity: 20,
      previousStock: 0,
      updatedStock: 20,
      userId: 'usr-admin',
      userName: 'Sardar Manjit Singh',
      remarks: 'Opening inventory load',
      date: '2026-01-05T10:30:00.000Z',
    },
    {
      id: 'stk-3',
      productId: 'prod-6',
      productName: 'Castrol EDGE 5W-40 Fully Synthetic Engine Oil (4L)',
      type: 'opening',
      quantity: 30,
      previousStock: 0,
      updatedStock: 30,
      userId: 'usr-admin',
      userName: 'Sardar Manjit Singh',
      remarks: 'Opening distributor delivery',
      date: '2026-01-08T11:00:00.000Z',
    },
    {
      id: 'stk-4',
      productId: 'prod-1',
      productName: 'Exide Mileage MLDIN45L (45 Ah) Car Battery',
      type: 'sale',
      quantity: -1,
      previousStock: 25,
      updatedStock: 24,
      referenceNo: 'SMA-2026-1001',
      userId: 'usr-staff',
      userName: 'Rohan Sharma',
      remarks: 'Sold in Invoice SMA-2026-1001',
      date: '2026-09-10T14:30:00.000Z',
    },
  ];

  const defaultInvoices: Invoice[] = [
    {
      id: 'inv-1001',
      invoiceNumber: 'SMA-2026-1001',
      date: '2026-09-10T14:30:00.000Z',
      customerId: 'cust-1',
      customerName: 'Verma Motors & Multi-Brand Workshop',
      customerPhone: '9810123456',
      customerGstin: '07AADFV5566K1Z9',
      billingAddress: 'Plot 10, Auto Cluster, Sector 18, Rohini, Delhi',
      shippingAddress: 'Plot 10, Auto Cluster, Sector 18, Rohini, Delhi',
      isInterState: false,
      items: [
        {
          id: 'item-1',
          productId: 'prod-1',
          productName: 'Exide Mileage MLDIN45L (45 Ah) Car Battery',
          sku: 'BAT-EX-MI45L',
          barcode: '890123400101',
          quantity: 2,
          unit: 'Nos',
          rate: 5100,
          mrp: 6499,
          discountPercent: 0,
          discountAmount: 0,
          taxableAmount: 10200,
          gstRate: 28,
          cgstAmount: 1428,
          sgstAmount: 1428,
          igstAmount: 0,
          totalAmount: 13056,
        },
        {
          id: 'item-2',
          productId: 'prod-6',
          productName: 'Castrol EDGE 5W-40 Fully Synthetic Engine Oil (4L)',
          sku: 'OIL-CAS-EDG5W40',
          barcode: '890123400106',
          quantity: 2,
          unit: 'Nos',
          rate: 3200,
          mrp: 3899,
          discountPercent: 0,
          discountAmount: 0,
          taxableAmount: 6400,
          gstRate: 18,
          cgstAmount: 576,
          sgstAmount: 576,
          igstAmount: 0,
          totalAmount: 7552,
        },
      ],
      subtotal: 16600,
      overallDiscountType: 'fixed',
      overallDiscountValue: 0,
      overallDiscountAmount: 0,
      taxableAmount: 16600,
      cgstTotal: 2004,
      sgstTotal: 2004,
      igstTotal: 0,
      roundOff: 0,
      grandTotal: 20608,
      paidAmount: 10000,
      balanceAmount: 10608,
      paymentMode: 'UPI',
      paymentStatus: 'Partially Paid',
      notes: 'Urgent delivery for workshop customer cars.',
      createdBy: 'Rohan Sharma',
      createdAt: '2026-09-10T14:30:00.000Z',
    },
    {
      id: 'inv-1002',
      invoiceNumber: 'SMA-2026-1002',
      date: '2026-09-11T11:15:00.000Z',
      customerId: 'cust-3',
      customerName: 'Rajesh Sharma',
      customerPhone: '9899001122',
      billingAddress: 'Flat 204, Pocket B, Ashok Vihar, Delhi',
      isInterState: false,
      items: [
        {
          id: 'item-3',
          productId: 'prod-2',
          productName: 'Amaron Flo AAM-FL-00042B20R (35 Ah) Battery',
          sku: 'BAT-AM-FLO35R',
          barcode: '890123400102',
          quantity: 1,
          unit: 'Nos',
          rate: 4100,
          mrp: 4999,
          discountPercent: 5,
          discountAmount: 205,
          taxableAmount: 3895,
          gstRate: 28,
          cgstAmount: 545.3,
          sgstAmount: 545.3,
          igstAmount: 0,
          totalAmount: 4985.6,
        },
        {
          id: 'item-4',
          productId: 'prod-12',
          productName: 'SM Battery Grade De-mineralized Distilled Water (5 Litres)',
          sku: 'ACC-DIST-5L',
          barcode: '890123400112',
          quantity: 1,
          unit: 'Nos',
          rate: 90,
          mrp: 120,
          discountPercent: 0,
          discountAmount: 0,
          taxableAmount: 90,
          gstRate: 12,
          cgstAmount: 5.4,
          sgstAmount: 5.4,
          igstAmount: 0,
          totalAmount: 100.8,
        },
      ],
      subtotal: 4190,
      overallDiscountAmount: 205,
      taxableAmount: 3985,
      cgstTotal: 550.7,
      sgstTotal: 550.7,
      igstTotal: 0,
      roundOff: 0.6,
      grandTotal: 5087,
      paidAmount: 5087,
      balanceAmount: 0,
      paymentMode: 'Cash',
      paymentStatus: 'Paid',
      notes: 'Car battery replaced with warranty card issued.',
      createdBy: 'Sardar Manjit Singh',
      createdAt: '2026-09-11T11:15:00.000Z',
    },
    {
      id: 'inv-1003',
      invoiceNumber: 'SMA-2026-1003',
      date: '2026-09-12T16:45:00.000Z',
      customerId: 'cust-5',
      customerName: 'Manish Tyagi',
      customerPhone: '9822334455',
      billingAddress: 'House 88, Model Town 2, Delhi',
      isInterState: false,
      items: [
        {
          id: 'item-5',
          productId: 'prod-4',
          productName: 'Exide Xplore 12XL9-B (9 Ah) Heavy Bike Battery',
          sku: 'BAT-EX-XP9B',
          barcode: '890123400104',
          quantity: 1,
          unit: 'Nos',
          rate: 2150,
          mrp: 2650,
          discountPercent: 0,
          discountAmount: 0,
          taxableAmount: 2150,
          gstRate: 28,
          cgstAmount: 301,
          sgstAmount: 301,
          igstAmount: 0,
          totalAmount: 2752,
        },
        {
          id: 'item-6',
          productId: 'prod-7',
          productName: 'Motul 7100 4T 10W-50 100% Synthetic Bike Oil (1L)',
          sku: 'OIL-MOT-7100',
          barcode: '890123400107',
          quantity: 2,
          unit: 'Nos',
          rate: 980,
          mrp: 1190,
          discountPercent: 0,
          discountAmount: 0,
          taxableAmount: 1960,
          gstRate: 18,
          cgstAmount: 176.4,
          sgstAmount: 176.4,
          igstAmount: 0,
          totalAmount: 2312.8,
        },
      ],
      subtotal: 4110,
      overallDiscountAmount: 0,
      taxableAmount: 4110,
      cgstTotal: 477.4,
      sgstTotal: 477.4,
      igstTotal: 0,
      roundOff: 0.2,
      grandTotal: 5065,
      paidAmount: 5065,
      balanceAmount: 0,
      paymentMode: 'UPI',
      paymentStatus: 'Paid',
      notes: 'RE Classic 350 service parts.',
      createdBy: 'Rohan Sharma',
      createdAt: '2026-09-12T16:45:00.000Z',
    },
    {
      id: 'inv-1004',
      invoiceNumber: 'SMA-2026-1004',
      date: '2026-09-13T09:15:00.000Z',
      customerId: 'cust-2',
      customerName: 'Vikas Auto Clinic',
      customerPhone: '9871234560',
      billingAddress: 'Shop 4, Near Metro Pillar 321, GT Road, Delhi',
      isInterState: false,
      items: [
        {
          id: 'item-7',
          productId: 'prod-8',
          productName: 'Bosch Front Disc Brake Pads Set for Maruti Swift / Dzire',
          sku: 'BRK-BOS-SWF',
          barcode: '890123400108',
          quantity: 2,
          unit: 'Sets',
          rate: 950,
          mrp: 1250,
          discountPercent: 0,
          discountAmount: 0,
          taxableAmount: 1900,
          gstRate: 18,
          cgstAmount: 171,
          sgstAmount: 171,
          igstAmount: 0,
          totalAmount: 2242,
        },
        {
          id: 'item-8',
          productId: 'prod-10',
          productName: 'Roots Windtone Sonic Dual Horn Set (12V)',
          sku: 'ELC-ROO-WND',
          barcode: '890123400110',
          quantity: 1,
          unit: 'Sets',
          rate: 890,
          mrp: 1150,
          discountPercent: 0,
          discountAmount: 0,
          taxableAmount: 890,
          gstRate: 18,
          cgstAmount: 80.1,
          sgstAmount: 80.1,
          igstAmount: 0,
          totalAmount: 1050.2,
        },
      ],
      subtotal: 2790,
      overallDiscountAmount: 0,
      taxableAmount: 2790,
      cgstTotal: 251.1,
      sgstTotal: 251.1,
      igstTotal: 0,
      roundOff: -0.2,
      grandTotal: 3292,
      paidAmount: 2000,
      balanceAmount: 1292,
      paymentMode: 'Multiple',
      paymentStatus: 'Partially Paid',
      notes: 'Balance added to workshop ledger.',
      createdBy: 'Rohan Sharma',
      createdAt: '2026-09-13T09:15:00.000Z',
    },
  ];

  const defaultPayments: Payment[] = [
    {
      id: 'pay-1',
      invoiceId: 'inv-1001',
      invoiceNumber: 'SMA-2026-1001',
      customerId: 'cust-1',
      customerName: 'Verma Motors & Multi-Brand Workshop',
      amount: 10000,
      paymentMode: 'UPI',
      transactionRef: 'UPI/HDFC/6290128911',
      date: '2026-09-10T14:35:00.000Z',
      notes: 'Initial part payment via Google Pay',
      createdBy: 'Rohan Sharma',
    },
    {
      id: 'pay-2',
      invoiceId: 'inv-1002',
      invoiceNumber: 'SMA-2026-1002',
      customerId: 'cust-3',
      customerName: 'Rajesh Sharma',
      amount: 5087,
      paymentMode: 'Cash',
      date: '2026-09-11T11:18:00.000Z',
      notes: 'Counter cash received',
      createdBy: 'Sardar Manjit Singh',
    },
    {
      id: 'pay-3',
      invoiceId: 'inv-1003',
      invoiceNumber: 'SMA-2026-1003',
      customerId: 'cust-5',
      customerName: 'Manish Tyagi',
      amount: 5065,
      paymentMode: 'UPI',
      transactionRef: 'PAYTM/UPI/99881122',
      date: '2026-09-12T16:48:00.000Z',
      notes: 'Instant UPI transfer',
      createdBy: 'Rohan Sharma',
    },
    {
      id: 'pay-4',
      invoiceId: 'inv-1004',
      invoiceNumber: 'SMA-2026-1004',
      customerId: 'cust-2',
      customerName: 'Vikas Auto Clinic',
      amount: 2000,
      paymentMode: 'Cash',
      date: '2026-09-13T09:16:00.000Z',
      notes: 'Part cash payment on delivery',
      createdBy: 'Rohan Sharma',
    },
  ];

  const defaultCustomerLedgers: CustomerLedgerEntry[] = [
    {
      id: 'cld-1',
      customerId: 'cust-1',
      customerName: 'Verma Motors & Multi-Brand Workshop',
      date: '2026-09-10T14:30:00.000Z',
      description: 'Invoice SMA-2026-1001 Generated',
      type: 'invoice',
      referenceNo: 'SMA-2026-1001',
      debit: 20608,
      credit: 0,
      balance: 20608,
      notes: '2x Exide MLDIN45L, 2x Castrol Edge 4L',
    },
    {
      id: 'cld-2',
      customerId: 'cust-1',
      customerName: 'Verma Motors & Multi-Brand Workshop',
      date: '2026-09-10T14:35:00.000Z',
      description: 'UPI Payment Received Against SMA-2026-1001',
      type: 'payment',
      referenceNo: 'PAY-1',
      debit: 0,
      credit: 10000,
      balance: 10608,
      notes: 'UPI/HDFC/6290128911',
    },
    {
      id: 'cld-3',
      customerId: 'cust-2',
      customerName: 'Vikas Auto Clinic',
      date: '2026-09-13T09:15:00.000Z',
      description: 'Invoice SMA-2026-1004 Generated',
      type: 'invoice',
      referenceNo: 'SMA-2026-1004',
      debit: 3292,
      credit: 0,
      balance: 10192,
      notes: 'Brake pads & Roots Windtone Horns',
    },
    {
      id: 'cld-4',
      customerId: 'cust-2',
      customerName: 'Vikas Auto Clinic',
      date: '2026-09-13T09:16:00.000Z',
      description: 'Cash Payment Against SMA-2026-1004',
      type: 'payment',
      referenceNo: 'PAY-4',
      debit: 0,
      credit: 2000,
      balance: 8192,
      notes: 'Cash payment',
    },
  ];

  const defaultSupplierLedgers: SupplierLedgerEntry[] = [
    {
      id: 'sld-1',
      supplierId: 'sup-1',
      supplierName: 'Exide Industries Ltd - Regional Depot',
      date: '2026-01-05T10:00:00.000Z',
      description: 'Stock Purchase Batch EX-DEL-892',
      type: 'purchase',
      referenceNo: 'BILL-EX-892',
      debit: 0,
      credit: 135000,
      balance: 135000,
      notes: 'Initial battery consignment',
    },
    {
      id: 'sld-2',
      supplierId: 'sup-1',
      supplierName: 'Exide Industries Ltd - Regional Depot',
      date: '2026-01-20T16:00:00.000Z',
      description: 'RTGS Payment to Exide Industries',
      type: 'payment',
      referenceNo: 'RTGS-HDFC-9912',
      debit: 100000,
      credit: 0,
      balance: 35000,
      notes: 'Part clearance of Bill EX-DEL-892',
    },
  ];

  const defaultAuditLogs: AuditLog[] = [
    {
      id: 'log-1',
      userId: 'usr-admin',
      userName: 'Sardar Manjit Singh',
      action: 'SYSTEM_INITIALIZATION',
      module: 'Settings',
      details: 'SM Autos & Batteries ERP initialized with master categories and stock',
      timestamp: '2026-01-01T08:00:00.000Z',
    },
    {
      id: 'log-2',
      userId: 'usr-staff',
      userName: 'Rohan Sharma',
      action: 'INVOICE_CREATED',
      module: 'Billing',
      recordId: 'SMA-2026-1001',
      details: 'Created Invoice SMA-2026-1001 for Verma Motors (₹20,608)',
      timestamp: '2026-09-10T14:30:00.000Z',
    },
  ];

  return {
    users: defaultUsers,
    categories: defaultCategories,
    products: defaultProducts,
    customers: defaultCustomers,
    suppliers: defaultSuppliers,
    invoices: defaultInvoices,
    payments: defaultPayments,
    stockTransactions: defaultStockTransactions,
    customerLedgers: defaultCustomerLedgers,
    supplierLedgers: defaultSupplierLedgers,
    returns: [],
    settings: defaultSettings,
    auditLogs: defaultAuditLogs,
  };
}

export function readDb(): DatabaseSchema {
  if (dbCache) return dbCache;
  ensureDataDir();
  if (!fs.existsSync(DB_FILE)) {
    const initial = getInitialData();
    fs.writeFileSync(DB_FILE, JSON.stringify(initial, null, 2), 'utf-8');
    dbCache = initial;
    return dbCache;
  }
  try {
    const raw = fs.readFileSync(DB_FILE, 'utf-8');
    dbCache = JSON.parse(raw);
    return dbCache!;
  } catch (err) {
    console.error('Failed to parse db.json, generating fresh default:', err);
    const initial = getInitialData();
    fs.writeFileSync(DB_FILE, JSON.stringify(initial, null, 2), 'utf-8');
    dbCache = initial;
    return dbCache;
  }
}

export function writeDb(data: DatabaseSchema) {
  ensureDataDir();
  dbCache = data;
  fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2), 'utf-8');
}

export function logAudit(userId: string, userName: string, action: string, module: string, details: string, recordId?: string) {
  const db = readDb();
  const log: AuditLog = {
    id: `log-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
    userId,
    userName,
    action,
    module,
    recordId,
    details,
    timestamp: new Date().toISOString(),
  };
  db.auditLogs.unshift(log);
  if (db.auditLogs.length > 500) {
    db.auditLogs = db.auditLogs.slice(0, 500);
  }
  writeDb(db);
}
