import { db } from './db.js';

export const categoriesToSeed = [
  { id: 'cat-car-suv', name: 'Car & SUV Batteries', description: 'Automotive batteries for cars, SUVs, and light vehicles', icon: 'Car' },
  { id: 'cat-2w', name: '2-Wheeler Batteries', description: 'Batteries for motorcycles, scooters, and 2-wheelers', icon: 'Bike' },
  { id: 'cat-comm-trac', name: 'Commercial & Tractor Batteries', description: 'Heavy duty batteries for trucks, buses, tractors, and commercial vehicles', icon: 'Truck' },
  { id: 'cat-erickshaw', name: 'E-Rickshaw Batteries', description: 'Tubular, Flat, and Lithium-ion batteries & chargers for E-Rickshaws', icon: 'Zap' },
  { id: 'cat-accessories', name: 'Battery Accessories', description: 'Distilled water, battery acid, cables, and maintenance products', icon: 'Droplet' },
];

export const sfProducts = [
  // --- CAR / SUV BATTERIES ---
  {
    sku: 'F2S-35P',
    name: 'SF 4W Series 72 - F2S-35P (35Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-35P',
    description: 'SF 4W Series 72 Car/SUV Battery 35Ah. Warranty: 42F+30P (72 Months)',
    mrp: 8208,
    retailPrice: 8208,
    wholesalePrice: 5830,
    sellingPrice: 5830,
    purchasePrice: 4500,
    gstRate: 28,
    warrantyPeriod: '72 Months (42F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-42B20L',
    name: 'SF 4W Series 72 - F2S-42B20L (42Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-42B20L',
    description: 'SF 4W Series 72 Car/SUV Battery 42Ah. Warranty: 42F+30P (72 Months)',
    mrp: 8299,
    retailPrice: 8299,
    wholesalePrice: 5907,
    sellingPrice: 5907,
    purchasePrice: 4600,
    gstRate: 28,
    warrantyPeriod: '72 Months (42F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-DNT74L',
    name: 'SF 4W Series 72 - F2S-DNT74L (74Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-DNT74L',
    description: 'SF 4W Series 72 Car/SUV Battery 74Ah. Warranty: 42F+30P (72 Months)',
    mrp: 13885,
    retailPrice: 13885,
    wholesalePrice: 9873,
    sellingPrice: 9873,
    purchasePrice: 7800,
    gstRate: 28,
    warrantyPeriod: '72 Months (42F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-DNT100',
    name: 'SF 4W Series 72 - F2S-DNT100 (100Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-DNT100',
    description: 'SF 4W Series 72 Car/SUV Battery 100Ah. Warranty: 42F+30P (72 Months)',
    mrp: 20875,
    retailPrice: 20875,
    wholesalePrice: 14881,
    sellingPrice: 14881,
    purchasePrice: 11500,
    gstRate: 28,
    warrantyPeriod: '72 Months (42F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-60D26L',
    name: 'SF 4W Series 60 - F2S-60D26L (60Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-60D26L',
    description: 'SF 4W Series 60 Car/SUV Battery 60Ah. Warranty: 36F+24P (60 Months)',
    mrp: 9890,
    retailPrice: 9890,
    wholesalePrice: 6985,
    sellingPrice: 6985,
    purchasePrice: 5400,
    gstRate: 28,
    warrantyPeriod: '60 Months (36F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-65D26R',
    name: 'SF 4W Series 60 - F2S-65D26R (65Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-65D26R',
    description: 'SF 4W Series 60 Car/SUV Battery 65Ah. Warranty: 36F+24P (60 Months)',
    mrp: 9933,
    retailPrice: 9933,
    wholesalePrice: 7015,
    sellingPrice: 7015,
    purchasePrice: 5450,
    gstRate: 28,
    warrantyPeriod: '60 Months (36F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-35B20R/L',
    name: 'SF 4W Series 60 - F2S-35B20R/L (35Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-35B20R/L',
    description: 'SF 4W Series 60 Car/SUV Battery 35Ah. Warranty: 30F+30P (60 Months)',
    mrp: 7305,
    retailPrice: 7305,
    wholesalePrice: 5160,
    sellingPrice: 5160,
    purchasePrice: 4000,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-F500L',
    name: 'SF 4W Series 60 - F2S-F500L (50Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-F500L',
    description: 'SF 4W Series 60 Car/SUV Battery 50Ah. Warranty: 30F+30P (60 Months)',
    mrp: 7439,
    retailPrice: 7439,
    wholesalePrice: 5263,
    sellingPrice: 5263,
    purchasePrice: 4100,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-55D23L',
    name: 'SF 4W Series 60 - F2S-55D23L (54Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-55D23L',
    description: 'SF 4W Series 60 Car/SUV Battery 54Ah. Warranty: 30F+30P (60 Months)',
    mrp: 7562,
    retailPrice: 7562,
    wholesalePrice: 5348,
    sellingPrice: 5348,
    purchasePrice: 4150,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-F600R/L',
    name: 'SF 4W Series 60 - F2S-F600R/L (60Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-F600R/L',
    description: 'SF 4W Series 60 Car/SUV Battery 60Ah. Warranty: 30F+30P (60 Months)',
    mrp: 8740,
    retailPrice: 8740,
    wholesalePrice: 6183,
    sellingPrice: 6183,
    purchasePrice: 4800,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-F680R/L',
    name: 'SF 4W Series 60 - F2S-F680R/L (68Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-F680R/L',
    description: 'SF 4W Series 60 Car/SUV Battery 68Ah. Warranty: 30F+30P (60 Months)',
    mrp: 9514,
    retailPrice: 9514,
    wholesalePrice: 6731,
    sellingPrice: 6731,
    purchasePrice: 5200,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-DNT72',
    name: 'SF 4W Series 60 - F2S-DNT72 (72Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-DNT72',
    description: 'SF 4W Series 60 Car/SUV Battery 72Ah. Warranty: 30F+30P (60 Months)',
    mrp: 12599,
    retailPrice: 12599,
    wholesalePrice: 8914,
    sellingPrice: 8914,
    purchasePrice: 6900,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-DNT80L',
    name: 'SF 4W Series 60 - F2S-DNT80L (80Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-DNT80L',
    description: 'SF 4W Series 60 Car/SUV Battery 80Ah. Warranty: 30F+30P (60 Months)',
    mrp: 12999,
    retailPrice: 12999,
    wholesalePrice: 9198,
    sellingPrice: 9198,
    purchasePrice: 7100,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-HX60L',
    name: 'SF Hybrid X - F2S-HX60L (60Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-HX60L',
    description: 'SF Hybrid X Car/SUV Battery 60Ah. Warranty: 30F+30P (60 Months)',
    mrp: 9910,
    retailPrice: 9910,
    wholesalePrice: 6995,
    sellingPrice: 6995,
    purchasePrice: 5400,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-HX70',
    name: 'SF Hybrid X - F2S-HX70 (70Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-HX70',
    description: 'SF Hybrid X Car/SUV Battery 70Ah. Warranty: 30F+30P (60 Months)',
    mrp: 10880,
    retailPrice: 10880,
    wholesalePrice: 7680,
    sellingPrice: 7680,
    purchasePrice: 5900,
    gstRate: 28,
    warrantyPeriod: '60 Months (30F+30P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-HX47L',
    name: 'SF Hybrid X - F2S-HX47L (47Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-HX47L',
    description: 'SF Hybrid X Car/SUV Battery 47Ah. Warranty: 24F+24P (48 Months)',
    mrp: 6842,
    retailPrice: 6842,
    wholesalePrice: 4831,
    sellingPrice: 4831,
    purchasePrice: 3750,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-HX52',
    name: 'SF Hybrid X - F2S-HX52 (52Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-HX52',
    description: 'SF Hybrid X Car/SUV Battery 52Ah. Warranty: 24F+24P (48 Months)',
    mrp: 7147,
    retailPrice: 7147,
    wholesalePrice: 5047,
    sellingPrice: 5047,
    purchasePrice: 3900,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-HX72R',
    name: 'SF Hybrid X - F2S-HX72R (72Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-HX72R',
    description: 'SF Hybrid X Car/SUV Battery 72Ah. Warranty: 24F+24P (48 Months)',
    mrp: 10598,
    retailPrice: 10598,
    wholesalePrice: 7481,
    sellingPrice: 7481,
    purchasePrice: 5800,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-32B20R/L',
    name: 'SF 4W Series 44 - F2S-32B20R/L (32Ah) NEW',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-32B20R/L',
    description: 'SF 4W Series 44 Car/SUV Battery 32Ah (NEW). Warranty: 24F+20P (44 Months)',
    mrp: 6120,
    retailPrice: 6120,
    wholesalePrice: 4284,
    sellingPrice: 4284,
    purchasePrice: 3300,
    gstRate: 28,
    warrantyPeriod: '44 Months (24F+20P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-F350R/L',
    name: 'SF 4W Series 44 - F2S-F350R/L (35Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-F350R/L',
    description: 'SF 4W Series 44 Car/SUV Battery 35Ah. Warranty: 24F+20P (44 Months)',
    mrp: 6420,
    retailPrice: 6420,
    wholesalePrice: 4494,
    sellingPrice: 4494,
    purchasePrice: 3500,
    gstRate: 28,
    warrantyPeriod: '44 Months (24F+20P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-F400R/L',
    name: 'SF 4W Series 44 - F2S-F400R/L (40Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-F400R/L',
    description: 'SF 4W Series 44 Car/SUV Battery 40Ah. Warranty: 24F+20P (44 Months)',
    mrp: 6118,
    retailPrice: 6118,
    wholesalePrice: 4283,
    sellingPrice: 4283,
    purchasePrice: 3300,
    gstRate: 28,
    warrantyPeriod: '44 Months (24F+20P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-F550R/L',
    name: 'SF 4W Series 44 - F2S-F550R/L (55Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-F550R/L',
    description: 'SF 4W Series 44 Car/SUV Battery 55Ah. Warranty: 24F+20P (44 Months)',
    mrp: 8118,
    retailPrice: 8118,
    wholesalePrice: 5683,
    sellingPrice: 5683,
    purchasePrice: 4400,
    gstRate: 28,
    warrantyPeriod: '44 Months (24F+20P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-F650R/L',
    name: 'SF 4W Series 44 - F2S-F650R/L (65Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-F650R/L',
    description: 'SF 4W Series 44 Car/SUV Battery 65Ah. Warranty: 24F+20P (44 Months)',
    mrp: 8868,
    retailPrice: 8868,
    wholesalePrice: 6208,
    sellingPrice: 6208,
    purchasePrice: 4800,
    gstRate: 28,
    warrantyPeriod: '44 Months (24F+20P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-DNT65R/L',
    name: 'SF 4W Series 44 - F2S-DNT65R/L (65Ah)',
    category: 'Car & SUV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-DNT65R/L',
    description: 'SF 4W Series 44 Car/SUV Battery 65Ah. Warranty: 24F+20P (44 Months)',
    mrp: 8767,
    retailPrice: 8767,
    wholesalePrice: 6137,
    sellingPrice: 6137,
    purchasePrice: 4750,
    gstRate: 28,
    warrantyPeriod: '44 Months (24F+20P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },

  // --- 3W & AUTO / LCV BATTERIES ---
  {
    sku: 'F2S-32B20L-3W',
    name: 'SF AutoRider Series 30 - F2S-32B20L (35Ah)',
    category: '3W & Auto / LCV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-32B20L',
    description: 'SF AutoRider Series 30 3W/Auto Battery 35Ah. Warranty: 18F+12P (30 Months)',
    mrp: 7425,
    retailPrice: 7425,
    wholesalePrice: 5223,
    sellingPrice: 5223,
    purchasePrice: 4000,
    gstRate: 28,
    warrantyPeriod: '30 Months (18F+12P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-DNT60L',
    name: 'SF AutoRider Series 24 - F2S-DNT60L (60Ah)',
    category: '3W & Auto / LCV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-DNT60L',
    description: 'SF AutoRider Series 24 3W/LCV Battery 60Ah. Warranty: 12F+12P (24 Months)',
    mrp: 8118,
    retailPrice: 8118,
    wholesalePrice: 5683,
    sellingPrice: 5683,
    purchasePrice: 4400,
    gstRate: 28,
    warrantyPeriod: '24 Months (12F+12P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-600L',
    name: 'SF AutoRider Series 12 - F2S-600L (50Ah)',
    category: '3W & Auto / LCV Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-600L',
    description: 'SF AutoRider Series 12 3W/LCV Battery 50Ah. Warranty: 12F (12 Months)',
    mrp: 5215,
    retailPrice: 5215,
    wholesalePrice: 3651,
    sellingPrice: 3651,
    purchasePrice: 2800,
    gstRate: 28,
    warrantyPeriod: '12 Months (12F)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },

  // --- COMMERCIAL & TRACTOR BATTERIES ---
  {
    sku: 'F2S-T800',
    name: 'SF Tracker Series 42 - F2S-T800 (80Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T800',
    description: 'SF Tracker Series 42 CV Battery 80Ah. Warranty: 24F+18P (42 Months)',
    mrp: 9012,
    retailPrice: 9012,
    wholesalePrice: 6373,
    sellingPrice: 6373,
    purchasePrice: 4900,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T880',
    name: 'SF Tracker Series 42 - F2S-T880 (88Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T880',
    description: 'SF Tracker Series 42 CV Battery 88Ah. Warranty: 24F+18P (42 Months)',
    mrp: 8677,
    retailPrice: 8677,
    wholesalePrice: 6136,
    sellingPrice: 6136,
    purchasePrice: 4750,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1000',
    name: 'SF Tracker Series 42 - F2S-T1000 (100Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1000',
    description: 'SF Tracker Series 42 CV Battery 100Ah. Warranty: 24F+18P (42 Months)',
    mrp: 12085,
    retailPrice: 12085,
    wholesalePrice: 8546,
    sellingPrice: 8546,
    purchasePrice: 6600,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1200',
    name: 'SF Tracker Series 42 - F2S-T1200 (120Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1200',
    description: 'SF Tracker Series 42 CV Battery 120Ah. Warranty: 24F+18P (42 Months)',
    mrp: 12912,
    retailPrice: 12912,
    wholesalePrice: 9131,
    sellingPrice: 9131,
    purchasePrice: 7100,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1300-NEW',
    name: 'SF Tracker Series 42 - F2S-T1300 (130Ah) NEW',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1300',
    description: 'SF Tracker Series 42 CV Battery 130Ah (NEW). Warranty: 24F+18P (42 Months)',
    mrp: 12917,
    retailPrice: 12917,
    wholesalePrice: 9087,
    sellingPrice: 9087,
    purchasePrice: 7050,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1400',
    name: 'SF Tracker Series 42 - F2S-T1400 (140Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1400',
    description: 'SF Tracker Series 42 CV Battery 140Ah. Warranty: 24F+18P (42 Months)',
    mrp: 12824,
    retailPrice: 12824,
    wholesalePrice: 9020,
    sellingPrice: 9020,
    purchasePrice: 7000,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1500',
    name: 'SF Tracker Series 42 - F2S-T1500 (150Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1500',
    description: 'SF Tracker Series 42 CV Battery 150Ah. Warranty: 24F+18P (42 Months)',
    mrp: 14280,
    retailPrice: 14280,
    wholesalePrice: 10044,
    sellingPrice: 10044,
    purchasePrice: 7800,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1800',
    name: 'SF Tracker Series 42 - F2S-T1800 (180Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1800',
    description: 'SF Tracker Series 42 CV Battery 180Ah. Warranty: 24F+18P (42 Months)',
    mrp: 18853,
    retailPrice: 18853,
    wholesalePrice: 13323,
    sellingPrice: 13323,
    purchasePrice: 10300,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T750R/L',
    name: 'SF Tracker Series 30 - F2S-T750R/L (75Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T750R/L',
    description: 'SF Tracker Series 30 CV Battery 75Ah. Warranty: 18F+12P (30 Months)',
    mrp: 7457,
    retailPrice: 7457,
    wholesalePrice: 5274,
    sellingPrice: 5274,
    purchasePrice: 4100,
    gstRate: 28,
    warrantyPeriod: '30 Months (18F+12P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1000R/L',
    name: 'SF Tracker Series 30 - F2S-T1000R/L (100Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1000R/L',
    description: 'SF Tracker Series 30 CV Battery 100Ah. Warranty: 18F+12P (30 Months)',
    mrp: 9131,
    retailPrice: 9131,
    wholesalePrice: 6458,
    sellingPrice: 6458,
    purchasePrice: 5000,
    gstRate: 28,
    warrantyPeriod: '30 Months (18F+12P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1300-30M',
    name: 'SF Tracker Series 30 - F2S-T1300 (130Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1300',
    description: 'SF Tracker Series 30 CV Battery 130Ah. Warranty: 18F+12P (30 Months)',
    mrp: 11217,
    retailPrice: 11217,
    wholesalePrice: 7887,
    sellingPrice: 7887,
    purchasePrice: 6100,
    gstRate: 28,
    warrantyPeriod: '30 Months (18F+12P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1500-30M',
    name: 'SF Tracker Series 30 - F2S-T1500 (150Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1500',
    description: 'SF Tracker Series 30 CV Battery 150Ah. Warranty: 18F+12P (30 Months)',
    mrp: 13600,
    retailPrice: 13600,
    wholesalePrice: 9566,
    sellingPrice: 9566,
    purchasePrice: 7400,
    gstRate: 28,
    warrantyPeriod: '30 Months (18F+12P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T750R/L-TR',
    name: 'SF Tractor Series 42 - F2S-T750R/L (75Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T750R/L',
    description: 'SF Tractor Series 42 Tractor Battery 75Ah. Warranty: 24F+18P (42 Months)',
    mrp: 7816,
    retailPrice: 7816,
    wholesalePrice: 5528,
    sellingPrice: 5528,
    purchasePrice: 4300,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T880-TR',
    name: 'SF Tractor Series 42 - F2S-T880 (88Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T880',
    description: 'SF Tractor Series 42 Tractor Battery 88Ah. Warranty: 24F+18P (42 Months)',
    mrp: 8677,
    retailPrice: 8677,
    wholesalePrice: 6136,
    sellingPrice: 6136,
    purchasePrice: 4750,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T900R/L',
    name: 'SF Tractor Series 42 - F2S-T900R/L (90Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T900R/L',
    description: 'SF Tractor Series 42 Tractor Battery 90Ah. Warranty: 24F+18P (42 Months)',
    mrp: 8824,
    retailPrice: 8824,
    wholesalePrice: 6240,
    sellingPrice: 6240,
    purchasePrice: 4850,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T1000L-TR',
    name: 'SF Tractor Series 42 - F2S-T1000L (100Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T1000L',
    description: 'SF Tractor Series 42 Tractor Battery 100Ah. Warranty: 24F+18P (42 Months)',
    mrp: 9932,
    retailPrice: 9932,
    wholesalePrice: 7023,
    sellingPrice: 7023,
    purchasePrice: 5450,
    gstRate: 28,
    warrantyPeriod: '42 Months (24F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-T800L-TR',
    name: 'SF Tractor Series 36 - F2S-T800L (80Ah)',
    category: 'Commercial & Tractor Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-T800L',
    description: 'SF Tractor Series 36 Tractor Battery 80Ah. Warranty: 18F+18P (36 Months)',
    mrp: 8047,
    retailPrice: 8047,
    wholesalePrice: 5690,
    sellingPrice: 5690,
    purchasePrice: 4400,
    gstRate: 28,
    warrantyPeriod: '36 Months (18F+18P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },

  // --- 2-WHEELER BATTERIES ---
  {
    sku: 'F2S-TZ2.5L',
    name: 'SF 2W Series 48 - F2S-TZ2.5L (2.5Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ2.5L',
    description: 'SF 2W Series 48 2-Wheeler Battery 2.5Ah. Warranty: 24F+24P (48 Months)',
    mrp: 1028,
    retailPrice: 1028,
    wholesalePrice: 725,
    sellingPrice: 725,
    purchasePrice: 560,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ3A',
    name: 'SF 2W Series 48 - F2S-TZ3A (3Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ3A',
    description: 'SF 2W Series 48 2-Wheeler Battery 3Ah. Warranty: 24F+24P (48 Months)',
    mrp: 1230,
    retailPrice: 1230,
    wholesalePrice: 867,
    sellingPrice: 867,
    purchasePrice: 670,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ4A',
    name: 'SF 2W Series 48 - F2S-TZ4A (4Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ4A',
    description: 'SF 2W Series 48 2-Wheeler Battery 4Ah. Warranty: 24F+24P (48 Months)',
    mrp: 1328,
    retailPrice: 1328,
    wholesalePrice: 937,
    sellingPrice: 937,
    purchasePrice: 725,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ5A/LB',
    name: 'SF 2W Series 48 - F2S-TZ5A/LB (5Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ5A/LB',
    description: 'SF 2W Series 48 2-Wheeler Battery 5Ah. Warranty: 24F+24P (48 Months)',
    mrp: 1531,
    retailPrice: 1531,
    wholesalePrice: 1080,
    sellingPrice: 1080,
    purchasePrice: 835,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ5',
    name: 'SF 2W Series 48 - F2S-TZ5 (5Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ5',
    description: 'SF 2W Series 48 2-Wheeler Battery 5Ah. Warranty: 24F+24P (48 Months)',
    mrp: 1602,
    retailPrice: 1602,
    wholesalePrice: 1130,
    sellingPrice: 1130,
    purchasePrice: 875,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ7',
    name: 'SF 2W Series 48 - F2S-TZ7 (7Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ7',
    description: 'SF 2W Series 48 2-Wheeler Battery 7Ah. Warranty: 24F+24P (48 Months)',
    mrp: 1988,
    retailPrice: 1988,
    wholesalePrice: 1402,
    sellingPrice: 1402,
    purchasePrice: 1085,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ9',
    name: 'SF 2W Series 48 - F2S-TZ9 (9Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ9',
    description: 'SF 2W Series 48 2-Wheeler Battery 9Ah. Warranty: 24F+24P (48 Months)',
    mrp: 2348,
    retailPrice: 2348,
    wholesalePrice: 1656,
    sellingPrice: 1656,
    purchasePrice: 1280,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ9B',
    name: 'SF 2W Series 48 - F2S-TZ9B (9Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ9B',
    description: 'SF 2W Series 48 2-Wheeler Battery 9Ah. Warranty: 24F+24P (48 Months)',
    mrp: 2338,
    retailPrice: 2338,
    wholesalePrice: 1649,
    sellingPrice: 1649,
    purchasePrice: 1275,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ12',
    name: 'SF 2W Series 48 - F2S-TZ12 (12Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ12',
    description: 'SF 2W Series 48 2-Wheeler Battery 12Ah. Warranty: 24F+24P (48 Months)',
    mrp: 3530,
    retailPrice: 3530,
    wholesalePrice: 2490,
    sellingPrice: 2490,
    purchasePrice: 1925,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-TZ14L-A2',
    name: 'SF 2W Series 48 - F2S-TZ14L-A2 (14Ah)',
    category: '2-Wheeler Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-TZ14L-A2',
    description: 'SF 2W Series 48 2-Wheeler Battery 14Ah. Warranty: 24F+24P (48 Months)',
    mrp: 3758,
    retailPrice: 3758,
    wholesalePrice: 2651,
    sellingPrice: 2651,
    purchasePrice: 2050,
    gstRate: 28,
    warrantyPeriod: '48 Months (24F+24P)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },

  // --- E-RICKSHAW BATTERIES & CHARGERS ---
  {
    sku: 'F2S-RT1500',
    name: 'SF E-Rickshaw Tubular - F2S-RT1500 (155Ah)',
    category: 'E-Rickshaw Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-RT1500',
    description: 'SF E-Rickshaw Rikshaw Tubular Battery 155Ah. Warranty: 12F (12 Months)',
    mrp: 13970,
    retailPrice: 13970,
    wholesalePrice: 9848,
    sellingPrice: 9848,
    purchasePrice: 7600,
    gstRate: 28,
    warrantyPeriod: '12 Months (12F)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-RT1600',
    name: 'SF E-Rickshaw Tubular - F2S-RT1600 (165Ah)',
    category: 'E-Rickshaw Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-RT1600',
    description: 'SF E-Rickshaw Rikshaw Tubular Battery 165Ah. Warranty: 12F (12 Months)',
    mrp: 14437,
    retailPrice: 14437,
    wholesalePrice: 10178,
    sellingPrice: 10178,
    purchasePrice: 7850,
    gstRate: 28,
    warrantyPeriod: '12 Months (12F)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-RF100',
    name: 'SF E-Rickshaw Flat - F2S-RF100 (100Ah)',
    category: 'E-Rickshaw Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-RF100',
    description: 'SF E-Rickshaw Rikshaw Flat Battery 100Ah. Warranty: 6F (6 Months)',
    mrp: 9156,
    retailPrice: 9156,
    wholesalePrice: 6455,
    sellingPrice: 6455,
    purchasePrice: 5000,
    gstRate: 28,
    warrantyPeriod: '6 Months (6F)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-RF120',
    name: 'SF E-Rickshaw Flat - F2S-RF120 (120Ah)',
    category: 'E-Rickshaw Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-RF120',
    description: 'SF E-Rickshaw Rikshaw Flat Battery 120Ah. Warranty: 6F (6 Months)',
    mrp: 9814,
    retailPrice: 9814,
    wholesalePrice: 6919,
    sellingPrice: 6919,
    purchasePrice: 5350,
    gstRate: 28,
    warrantyPeriod: '6 Months (6F)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-RF130',
    name: 'SF E-Rickshaw Flat - F2S-RF130 (130Ah)',
    category: 'E-Rickshaw Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-RF130',
    description: 'SF E-Rickshaw Rikshaw Flat Battery 130Ah. Warranty: 6F (6 Months)',
    mrp: 10871,
    retailPrice: 10871,
    wholesalePrice: 7664,
    sellingPrice: 7664,
    purchasePrice: 5900,
    gstRate: 28,
    warrantyPeriod: '6 Months (6F)',
    unit: 'Nos',
    openingStock: 10,
    currentStock: 10,
    minStockLevel: 2,
  },
  {
    sku: 'F2S-SERIES LFP 100',
    name: 'SF Recharge Lithium Ion Battery 51.2V 100Ah (NEW)',
    category: 'E-Rickshaw Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-SERIES LFP 100',
    description: 'SF E-Rickshaw Recharge Lithium Ion Battery 51.2V 100Ah (NEW). Warranty: 36 Months / FOC',
    mrp: 74680,
    retailPrice: 74680,
    wholesalePrice: 52896,
    sellingPrice: 52896,
    purchasePrice: 41000,
    gstRate: 18,
    warrantyPeriod: '36 Months / FOC',
    unit: 'Nos',
    openingStock: 5,
    currentStock: 5,
    minStockLevel: 1,
  },
  {
    sku: 'F2S-15115202001',
    name: 'SF Lithium Ion Battery Charger 48V 15A (NEW)',
    category: 'E-Rickshaw Batteries',
    brand: 'SF Batteries',
    modelNumber: 'F2S-15115202001',
    description: 'SF E-Rickshaw Lithium Ion Battery Charger 48V-15A (NEW). Warranty: 24 Months / FOC',
    mrp: 7750,
    retailPrice: 7750,
    wholesalePrice: 5488,
    sellingPrice: 5488,
    purchasePrice: 4250,
    gstRate: 18,
    warrantyPeriod: '24 Months / FOC',
    unit: 'Nos',
    openingStock: 5,
    currentStock: 5,
    minStockLevel: 1,
  },

  // --- ACCESSORIES & LIQUIDS ---
  {
    sku: 'F2S-DISTWATER 5L',
    name: 'SF Distilled Water 5L',
    category: 'Battery Accessories',
    brand: 'SF Batteries',
    modelNumber: 'F2S-DISTWATER 5L',
    description: 'SF Premium Distilled Water 5 Litres Container',
    mrp: 161,
    retailPrice: 161,
    wholesalePrice: 114,
    sellingPrice: 114,
    purchasePrice: 80,
    gstRate: 18,
    warrantyPeriod: 'N/A',
    unit: 'Litres',
    openingStock: 50,
    currentStock: 50,
    minStockLevel: 10,
  }
];

export async function runProductSeeder(): Promise<{ addedCount: number; updatedCount: number }> {
  console.log('[Seeder] Starting product & category seed...');
  const createdAt = new Date().toISOString();

  try {
    await db.sql`ALTER TABLE products ADD COLUMN wholesalePrice REAL`;
  } catch (_) {}
  try {
    await db.sql`ALTER TABLE products ADD COLUMN retailPrice REAL`;
  } catch (_) {}

  for (const cat of categoriesToSeed) {
    const existing = await db.sql`SELECT id FROM categories WHERE name = ${cat.name}`;
    if (!existing || existing.length === 0) {
      await db.sql`
        INSERT INTO categories (id, name, description, icon, productCount, createdAt)
        VALUES (${cat.id}, ${cat.name}, ${cat.description}, ${cat.icon}, 0, ${createdAt})
      `;
      console.log(`[Seeder] Created category: ${cat.name}`);
    }
  }

  let addedCount = 0;
  let updatedCount = 0;

  for (const p of sfProducts) {
    const existing = await db.sql`SELECT id FROM products WHERE sku = ${p.sku}`;
    const updatedAt = new Date().toISOString();

    const wholesalePrice = p.wholesalePrice ?? p.sellingPrice;
    const retailPrice = p.retailPrice ?? p.mrp ?? p.sellingPrice;

    if (existing && existing.length > 0) {
      const id = (existing as any[])[0].id;
      await db.sql`
        UPDATE products SET
          name = ${p.name},
          category = ${p.category},
          brand = ${p.brand},
          modelNumber = ${p.modelNumber},
          description = ${p.description},
          mrp = ${p.mrp},
          sellingPrice = ${wholesalePrice},
          wholesalePrice = ${wholesalePrice},
          retailPrice = ${retailPrice},
          purchasePrice = ${p.purchasePrice},
          gstRate = ${p.gstRate},
          warrantyPeriod = ${p.warrantyPeriod},
          unit = ${p.unit},
          updatedAt = ${updatedAt}
        WHERE id = ${id}
      `;
      updatedCount++;
    } else {
      const id = `prod-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;
      const barcode = `890${Math.floor(1000000000 + Math.random() * 9000000000)}`;
      await db.sql`
        INSERT INTO products (
          id, sku, name, category, brand, modelNumber, barcode, description,
          purchasePrice, sellingPrice, wholesalePrice, retailPrice, mrp, gstRate, discountPercent,
          openingStock, currentStock, minStockLevel, unit, warrantyPeriod, status,
          createdAt, updatedAt
        ) VALUES (
          ${id}, ${p.sku}, ${p.name}, ${p.category}, ${p.brand}, ${p.modelNumber}, ${barcode}, ${p.description},
          ${p.purchasePrice}, ${wholesalePrice}, ${wholesalePrice}, ${retailPrice}, ${p.mrp}, ${p.gstRate}, 0,
          ${p.openingStock}, ${p.currentStock}, ${p.minStockLevel}, ${p.unit}, ${p.warrantyPeriod}, 'active',
          ${createdAt}, ${updatedAt}
        )
      `;
      addedCount++;
    }
  }

  // Update category product counts
  for (const cat of categoriesToSeed) {
    const countRows = await db.sql`SELECT COUNT(*) as cnt FROM products WHERE category = ${cat.name}`;
    const count = countRows && countRows.length > 0 ? (countRows as any[])[0].cnt : 0;
    await db.sql`UPDATE categories SET productCount = ${count} WHERE name = ${cat.name}`;
  }

  console.log(`[Seeder] Seed complete. Added: ${addedCount}, Updated: ${updatedCount}`);
  return { addedCount, updatedCount };
}

if (process.argv[1] && process.argv[1].includes('seed_products')) {
  runProductSeeder().then((res) => {
    console.log('Seeding finished:', res);
    process.exit(0);
  }).catch((err) => {
    console.error('Seeding failed:', err);
    process.exit(1);
  });
}
